site_name: Update Documentation
site_url: https://sewer56.dev/Update/

repo_name: Sewer56/Update
repo_url: https://github.com/Sewer56/Update

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: slate
    
nav:
  - Home: index.md
  - Basic Usage: usage.md
  - Creating Releases: release-creation.md
  - CI/CD: ci-cd.md
  - Extensibility:
    - Custom Download Sources: extensibility/package-resolvers.md
    - Custom Extractors: extensibility/package-extractors.md
    - Custom Archivers: extensibility/package-archivers.md
    - Extra Package Metadata: extensibility/package-custom-metadata.md
  - Built-in Extensions:
    - Resolvers:
      - Aggregate Package Resolver: resolvers/aggregate-package-resolver.md
      - NuGet Package Resolver: resolvers/nuget-package-resolver.md
      - Local Package Resolver: resolvers/local-package-resolver.md
      - GitHub Release Resolver: resolvers/github-release-resolver.md
      - GameBanana Package Resolver: resolvers/gamebanana-package-resolver.md
    - Extractors & Archivers:
      - Zip Package: archivers/zip-package.md
      - SharpCompress: archivers/sharpcompress.md
      - NuGet: archivers/nuget.md
      - SevenZipSharp: archivers/sevenzipsharp.md
    